### ISSUE TITLE
docker pull recksato/robosats-client:v0.6.3-alpha results in an image with no main.js

### ISSUE THREAD

**Issue by gStart9** [RoboSats/robosats#1373]
**Describe the bug**
In an [attempt to update robosats-startos](https://github.com/RoboSats/robosats-startos/issues/22) for [StartOS](https://github.com/Start9Labs/start-os), we pull down the latest dockerhub `robosats-client` image.
Doing so results in an image with no main.js (attempting to load the front-end in a browser calls main.js but receives a 404

**To Reproduce**
1. `docker pull recksato/robosats-client:v0.6.3-alpha`
2. `docker run --rm --entrypoint="/bin/sh" -it recksato/robosats-client:v0.6.3-alpha`
3. `cd /usr/src/robosats/static/frontend`
4. `ls -al` and see that main.js is missing

**Expected behavior**
main.js should be there and requesting it via the browser should not result in a 404

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Browser: Firefox
 - Version: 127

**Comment by gStart9** [comment]
afaict this has been happening since v0.6.1

**Comment by gStart9** [comment]
Hi @Reckless-Satoshi or @KoalaSat

Do you have any idea what is going wrong here?  Is recksato/robosats-client:v0.6.3-alpha even the docker image I should be pulling?

When I try instead to pull in recksato/robosats:v0.6.3-alpha, and have it call:
/usr/src/robosats/scripts/entrypoint.sh

I get further but get python errors:
```
# sh -x /usr/src/robosats/scripts/entrypoint.sh
+ python manage.py migrate
Traceback (most recent call last):
  File "/usr/src/robosats/manage.py", line 22, in <module>
    main()
  File "/usr/src/robosats/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.12/site-packages/django/conf/__init__.py", line 89, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.12/site-packages/django/conf/__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/src/robosats/robosats/settings.py", line 30, in <module>
    SECRET_KEY = config("SECRET_KEY")
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/decouple.py", line 248, in __call__
    return self.config(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/decouple.py", line 107, in __call__
    return self.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/decouple.py", line 92, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.
+ [ ]
+ python manage.py collectstatic --noinput
Traceback (most recent call last):
  File "/usr/src/robosats/manage.py", line 22, in <module>
    main()
  File "/usr/src/robosats/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.12/site-packages/django/conf/__init__.py", line 89, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.12/site-packages/django/conf/__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/src/robosats/robosats/settings.py", line 30, in <module>
    SECRET_KEY = config("SECRET_KEY")
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/decouple.py", line 248, in __call__
    return self.config(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/decouple.py", line 107, in __call__
    return self.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/decouple.py", line 92, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.
+ [ ]
+ [ ! -f /usr/src/robosats/api/lightning/lightning_pb2.py ]
+ cp -R /tmp/hold_pb2.py /tmp/hold_pb2_grpc.py /tmp/invoices_pb2.py /tmp/invoices_pb2_grpc.py /tmp/lightning_pb2.py /tmp/lightning_pb2_grpc.py /tmp/node_pb2.py /tmp/node_pb2_grpc.py /tmp/primitives_pb2.py /tmp/primitives_pb2_grpc.py /tmp/router_pb2.py /tmp/router_pb2_grpc.py /tmp/signer_pb2.py /tmp/signer_pb2_grpc.py /tmp/verrpc_pb2.py /tmp/verrpc_pb2_grpc.py /usr/src/robosats/api/lightning/
+ exec
```

**Comment by KoalaSat** [comment]
```
SECRET_KEY not found
```

Seems like you don't have your ENV variables properly set

**Comment by gStart9** [comment]
Thanks for the reply.  I'm still confused though.  Is robosats-client supposed to have the main.js file?  Is robosats-client still a valid thing that is suppose to run?  I think the client is all we're needing in StartOS.  This more comprehensive `robosats` image seems to require a lot more stuff.

**Comment by KoalaSat** [comment]
Mmmm maybe we can ask @Reckless-Satoshi about it

**Comment by KoalaSat** [comment]
Hi @gStart9 , I spotted the issue, I got it running in this image https://hub.docker.com/layers/recksato/robosats-client/1ba8183/images/sha256-60bc9d364a084c33b9242003dda3c6fe8db1f4b7d3151f9686cd948724fd4ba0?context=explore

**Comment by gStart9** [comment]
That's awesome KoalaSat, I inserted that:
`FROM recksato/robosats-client:1ba8183`
into our container format and it worked this time!
Thanks so, so, so much!  Should we just pull this for 0.7.0-alpha or will there be an 0.7.1 soon?

**Comment by KoalaSat** [comment]
> That's awesome @KoalaSat, I inserted that: `FROM recksato/robosats-client:1ba8183` into our container format and it worked this time! Thanks so, so, so much! Should we just pull this for 0.7.0-alpha or will there be an 0.7.1 soon?

Next version is going to take some weeks to be out, let's move this one! 🚀

**Comment by gStart9** [comment]
I might have spoken slightly too soon.  main.js and most other things loaded but there might be a few more (nginx config?) issues:
![image](https://github.com/user-attachments/assets/0e4be870-6f4e-43bc-8ba7-5337fb5ecd99)

**Comment by KoalaSat** [comment]
Are only the /mainnet/exp endpoints reporting 404? That's the experimental coordinator which recently went down forever. We'll be probably removing the calls on the next version, but other than that, what you see its expected

**Comment by gStart9** [comment]
Yep those are the only errors, so I think we're good then. THANKS!!!
